### ISSUE TITLE
Slack plugin trackback on upgrade

### ISSUE THREAD

**Issue by Siecje** [getsentry/sentry#9452]
When upgrading from 8.22 to 9.0 there is a traceback in the upgrade output.

```shell
$ SENTRY_CONF=/etc/sentry sentry upgrade
Failed to load plugin 'slack':
Traceback (most recent call last):
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 31, in register_plugins
    plugin = ep.load()
  File "/home/sentry/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/home/sentry/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry_plugins/slack/plugin.py", line 8, in <module>
    from sentry.models import TagKey, TagValue
ImportError: cannot import name TagKey

Syncing...
```

**Comment by mattrobenolt** [comment]
You need to also upgrade `sentry-plugins` to 9.0.0 as well.
