### PR TITLE
fix(ui): Fix `<OrganizationTeams>` not listing all teams

### PR DESCRIPTION
**Pull request by billyvg**
This fixes a regression introduced in https://github.com/getsentry/sentry/pull/18067 when moving settings to
lightweight org tree. With the original org details, *ALL* teams were
included, with lightweight, we try to stub org.teams after org details is
fetched during the transition. However, the endpoint we use for this is
paginated, so this will break for orgs with many teams.

The solution is to replace usage of TeamsStore and `withTeams`, as these
stores depend on the FULL teams list. By replacing this, we need to ensure
that anywhere where we use teams, we need to make sure the UI supports a
paginated version of the teams list. In this case, we have a search filter
for the teams list, as well as limiting the number of teams returned on the
initial load.

This is what the "paginated" list looks like:
image

~Depends on https://github.com/getsentry/sentry/pull/18170~

### CODE REVIEW

File: src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx [hunk 1]
```diff
@@ -1,103 +0,0 @@
...
-  displayName: 'OrganizationTeamsContainer',
-
-  propTypes: {
-    api: PropTypes.object,
-    organization: SentryTypes.Organization,
-    routes: PropTypes.arrayOf(PropTypes.object),
-  },
-
-  mixins: [
-    Reflux.listenTo(TeamStore, 'onTeamListChange'),
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx:26]: Removed dependency on `TeamStore`, instead keep teams in state, use `user-teams` endpoint and `teams` endpoint with option to only include teams user is not a member of (this is needed for accurate pagination/filter). We don't actually paginate, but need to show a message when there are more available teams.

File: src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx [hunk 2]
```diff
@@ -1,103 +0,0 @@
...
-    Reflux.listenTo(ProjectsStore, 'onProjectListChange'),
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx:27]: Not even sure what this was used for since `this.state.projectList` was unused.

File: src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx [hunk 3]
```diff
@@ -1,103 +0,0 @@
...
-
-  getInitialState() {
-    return {
-      teamList: sortArray(TeamStore.getAll(), function(o) {
-        return o && o.name;
-      }),
-      projectList: sortArray(ProjectsStore.getAll(), function(o) {
-        return o && o.name;
-      }),
-      projectStats: {},
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx:38]: Both of these were unused.

File: src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx [hunk 4]
```diff
@@ -1,103 +0,0 @@
...
-
-  fetchStats() {
-    loadStats(this.props.api, {
-      orgId: this.props.params.orgId,
-      query: {
-        since: new Date().getTime() / 1000 - 3600 * 24,
-        stat: 'generated',
-        group: 'project',
-      },
-    });
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/settings/organizationTeams/index.jsx:54]: It's possible this loads data as a side effect for some other component, but because this component has state property of `projectsStats` and listened to the store, I assume it was intended for this component.

File: tests/js/spec/views/settings/organizationTeams/index.spec.jsx [hunk 5]
```diff
@@ -0,0 +1,230 @@
...
+import OrganizationTeams from 'app/views/settings/organizationTeams';
+import recreateRoute from 'app/utils/recreateRoute';
+
+recreateRoute.mockReturnValue('');
+
+jest.mock('app/actionCreators/modal', () => ({
+  openCreateTeamModal: jest.fn(),
+}));
+
+describe('OrganizationTeams', function() {
```
Comment (billyvg) [inline tests/js/spec/views/settings/organizationTeams/index.spec.jsx:15]: Used the same test cases, but integrated testing of container.

File: src/sentry/static/sentry/app/views/settings/organizationTeams/index.tsx [hunk 6]
```diff
@@ -0,0 +1,240 @@
...
+
+  async fetchActiveTeams() {
+    const {orgId} = this.props.params;
+
+    this.activeTeamsApi.clear();
+
+    try {
+      const resp = await this.activeTeamsApi.requestPromise(
+        `/organizations/${orgId}/user-teams/`
+      );
```
Comment (markstory) [inline src/sentry/static/sentry/app/views/settings/organizationTeams/index.tsx:67]: Do we need to worry about pagination with the active teams as well?

Comment (billyvg) [reply src/sentry/static/sentry/app/views/settings/organizationTeams/index.tsx:67]: The endpoint is not paginated - I looked at discover, and the endpoint generally responds fairly quickly, the only case where it doesn't is for superusers iirc.

**Review by markstory — APPROVED** [review]
