### PR TITLE
fix(superuser): allow superusers to invite members in other orgs

### PR DESCRIPTION
**Pull request by cathteng**
We recently did some work to refactor the invite members modal to a functional component (#63681).

Before this change, we were handling the case where superusers attempting to invite members on behalf of another organization (in which they weren't a member). This calls an endpoint that returns a 404 if the user is not a member of the organization. `DeprecatedAsyncComponent` handled this by setting the response value to `undefined`, thus setting the state variable that represents the API call to `undefined`. The new change always returns an error message if the status code of the response is some kind of error code.

We can fix the superuser case by checking for active superuser. If there is an error response (e.g. 404) from this particular endpoint and the user hitting it is active superuser, we can set the state variable to `undefined`.

### CODE REVIEW

File: static/app/components/modals/inviteMembersModal/index.tsx [hunk 1]
```diff
@@ -47,17 +48,25 @@ function InviteMembersModal({
     source,
   });
 
+  let member = memberResult.data;
```
Comment (ryan953) [inline static/app/components/modals/inviteMembersModal/index.tsx:51]:
```suggestion
```

Because of the early return on line 59 we don't need to use `let` for the variable. I would make sure that `member={...}` on line 96 has the correct value when we get to that line.

so if `member={memberResult.data}` doesn't work on its own, then `member={memberResult.data || undefined}` or something like that will. (but i think the former should work)

**Review by ryan953 — APPROVED** [review]

File: static/app/components/modals/inviteMembersModal/index.tsx (hunk 1 above)
Comment (cathteng) [reply static/app/components/modals/inviteMembersModal/index.tsx:51]: oh yea that works!
