### PR TITLE
 fix(dogstatsd): Fix crash when recording events 

### PR DESCRIPTION
**Pull request by untitaker**
found during INC-1413

error introduced by https://github.com/getsentry/sentry/commit/e2652bd26b3648f7631a162d254eeccde5237c32

code copied from other datadog backend

stacktrace ftr

```
"Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/utils/metrics.py", line 246, in event
    backend.event(
    ~~~~~~~~~~~~~^
        title,
        ^^^^^^
    ...<7 lines>...
        stacklevel + 1,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/sentry/src/sentry/metrics/middleware.py", line 209, in event
    return self.inner.event(
           ~~~~~~~~~~~~~~~~^
        title,
        ^^^^^^
    ...<7 lines>...
        stacklevel + 1,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/sentry/src/sentry/metrics/dualwrite.py", line 159, in event
    self._primary_backend.event(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        title,
        ^^^^^^
    ...<7 lines>...
        stacklevel + 1,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/sentry/src/sentry/metrics/dogstatsd.py", line 145, in event
    hostname=self.host,
             ^^^^^^^^^
AttributeError: 'DogStatsdMetricsBackend' object has no attribute 'host'"
```

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]

**Review by thetruecpaul — APPROVED** [review]
lgtm
