### PR TITLE
feat(weekly-report): add API endpoints and report filtering

### PR DESCRIPTION
**Pull request by amy-chen23**
Resolves [ID-1667](https://linear.app/getsentry/issue/ID-1667/create-api-endpoints-to-populate-weeklyreportprojectexclusion-db)

Goal: allow users to choose which projects they want to include in the weekly report.[ Previous PR (already merged) ](https://github.com/getsentry/sentry/pull/118522)created the model. This PR adds the API endpoints + exclusion filtering in `weekly_reports.py`.

Changes:
- Adds `GET/PUT /api/0/organizations/{org}/weekly-report-project-exclusions/` endpoints to list and bulk-update a user's excluded projects
- Adds `DELETE /api/0/organizations/{org}/weekly-report-project-exclusions/{project_id_or_slug}/` to remove a single exclusion. Use `PUT {"projectIds": []}` as bulk deletion
- Wires exclusion filtering into `prepare_template_context()` and `render_template_context()` in the weekly report task — one query per org batch, no mutation of shared `ctx.project_ownership`
- All endpoints gated behind `organizations:weekly-report-project-exclusions` feature flag (registered in PR1)

### CODE REVIEW

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+from sentry.models.weeklyreportprojectexclusion import WeeklyReportProjectExclusion
+
+
+@cell_silo_endpoint
+class OrganizationWeeklyReportProjectExclusionsEndpoint(OrganizationEndpoint):
+    publish_status = {
+        "GET": ApiPublishStatus.PRIVATE,
+        "PUT": ApiPublishStatus.PRIVATE,
+    }
+    owner = ApiOwner.ISSUE_DETECTION_BACKEND
```
Comment (amy-chen23) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py:31]: set issue detection as API owner

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+                {"detail": "projectIds must be a list of integers"},
+                status=status.HTTP_400_BAD_REQUEST,
+            )
+
+        if project_ids:
+            projects = self.get_projects(
+                request=request,
+                organization=organization,
+                project_ids=set(project_ids),
+            )
```
[the remark this answers is not in the document]
Comment (amy-chen23) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py]: using `self.get_projects` to validate seems to be the standard across sentry endpoints

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+            project = Project.objects.get(
+                organization_id=organization.id,
+                id=project_id,
+            )
+        except (ValueError, Project.DoesNotExist):
+            try:
+                project = Project.objects.get(
+                    organization_id=organization.id,
+                    slug=project_id_or_slug,
+                )
```
Comment (markstory) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py]: With this being a new endpoint could we pick a side on the id/slug type? Or do we need to support both?

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+    def put(self, request: Request, organization: Organization) -> Response:
+        if not features.has(
+            "organizations:weekly-report-project-exclusions", organization, actor=request.user
+        ):
+            return Response(status=status.HTTP_404_NOT_FOUND)
+
+        project_ids = request.data.get("projectIds", [])
+        if not isinstance(project_ids, list) or not all(
+            isinstance(pid, int) for pid in project_ids
+        ):
```
Comment (markstory) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py:65]: If this is id only, having the DELETE endpoint be id only would give you more symmetry in the endpoints.

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+
+        if project_ids:
+            projects = self.get_projects(
+                request=request,
+                organization=organization,
+                project_ids=set(project_ids),
+            )
+            validated_project_ids = {p.id for p in projects}
+        else:
+            validated_project_ids = set()
```
Comment (markstory) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py:81]: Should you raise an error if the `validated_project_ids` is a different size (smaller) than the request payload? That situation would indicate that the request contained projects that the user does not have access to, so a 200 could be a lie as their request was only partially applied.

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+                user_id=request.user.id,  # type: ignore[misc]
+                project__organization_id=organization.id,
+            ).delete()
+
+            if validated_project_ids:
+                WeeklyReportProjectExclusion.objects.bulk_create(
+                    [
+                        WeeklyReportProjectExclusion(
+                            project_id=pid,
+                            user_id=request.user.id,  # type: ignore[misc]
```
Comment (markstory) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py]: Instead of type ignores you can put `assert request.user` higher up in the method body to narrow the type on `request.user`.

File: tests/sentry/api/endpoints/test_organization_weekly_report_project_exclusions.py [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+                projectIds="not-a-list",
+            )
+        assert response.status_code == 400
+
+    def test_invalid_project_ids_non_integers(self) -> None:
+        with self.feature("organizations:weekly-report-project-exclusions"):
+            response = self.get_response(
+                self.organization.slug,
+                projectIds=["not-a-number"],
+            )
```
Comment (markstory) [inline tests/sentry/api/endpoints/test_organization_weekly_report_project_exclusions.py:124]: It would be good to have tests covering accessing projects the current user is not a member of, and projects in orgs that the user is not in.

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py (hunk 3 above)
Comment (cvxluo) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py]: i _think_ we're generally trying to accept both project ids and slugs in endpoints, as introduced in https://github.com/getsentry/sentry/pull/117445.

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+    def delete(
+        self, request: Request, organization: Organization, project_id_or_slug: str
+    ) -> Response:
+        if not features.has(
+            "organizations:weekly-report-project-exclusions", organization, actor=request.user
+        ):
+            return Response(status=status.HTTP_404_NOT_FOUND)
+
+        try:
+            project_id = int(project_id_or_slug)
```
Comment (cvxluo) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py]: you may be able to use the shared helper `parse_id_or_slug_params`

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+    owner = ApiOwner.ISSUE_DETECTION_BACKEND
+
+    def get(self, request: Request, organization: Organization) -> Response:
+        if not features.has(
+            "organizations:weekly-report-project-exclusions", organization, actor=request.user
+        ):
+            return Response(status=status.HTTP_404_NOT_FOUND)
+
+        queryset = WeeklyReportProjectExclusion.objects.filter(
+            user_id=request.user.id,  # type: ignore[misc]
```
Comment (cvxluo) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py]: why do we need the type ignore here?

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py (hunk 5 above)
Comment (amy-chen23) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py:81]: Yup, i think raising an error there would be more correct so that there aren't silent omissions

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py (hunk 9 above)
Comment (amy-chen23) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py]: typing issues, but mark raised a good point about adding `assert request.user` to the top of the method to get rid of the type ignores

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+
+        if not features.has(
+            "organizations:weekly-report-project-exclusions", organization, actor=request.user
+        ):
+            return Response(status=status.HTTP_404_NOT_FOUND)
+
+        project_ids = request.data.get("projectIds", [])
+        if not isinstance(project_ids, list) or not all(
+            isinstance(pid, int) for pid in project_ids
+        ):
```
[the remark this answers is not in the document]
Comment (amy-chen23) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusions.py:65]: fixing this seems overdefensive?

File: tests/sentry/api/endpoints/test_organization_weekly_report_project_exclusions.py [hunk 11]
```diff
@@ -0,0 +1,182 @@
...
+        self.login_as(user=self.user)
+
+    def test_empty(self) -> None:
+        with self.feature("organizations:weekly-report-project-exclusions"):
+            response = self.get_success_response(self.organization.slug)
+        assert response.data == []
+
+    def test_returns_exclusions(self) -> None:
+        project2 = self.create_project(organization=self.organization)
+        exc1 = WeeklyReportProjectExclusion.objects.create(
```
Comment (shashjar) [inline tests/sentry/api/endpoints/test_organization_weekly_report_project_exclusions.py]: might be worth creating a factory method/fixture for this so you don't have to directly do `WeeklyReportProjectExclusion.objects.create()`

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+    permission_classes = (OrganizationWeeklyReportProjectExclusionDetailsPermission,)
+    publish_status = {
+        "DELETE": ApiPublishStatus.PRIVATE,
+    }
+    owner = ApiOwner.ISSUE_DETECTION_BACKEND
+
+    def delete(
+        self, request: Request, organization: Organization, project_id_or_slug: str
+    ) -> Response:
+        assert request.user and request.user.id
```
Comment (shashjar) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py:32]: i think the auth middleware takes care of this, or did you need this to make mypy happy?

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py [hunk 13]
```diff
@@ -0,0 +1,59 @@
...
+
+        if not features.has(
+            "organizations:weekly-report-project-exclusions", organization, actor=request.user
+        ):
+            return Response(status=status.HTTP_404_NOT_FOUND)
+
+        parsed = parse_id_or_slug_params([project_id_or_slug])
+        if any(pid <= 0 for pid in parsed.ids):
+            return Response(status=status.HTTP_404_NOT_FOUND)
+        projects = self.get_projects(
```
Comment (shashjar) [inline src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py:42]: do we need to check whether the user has access to this project? i guess it doesn't really matter much for what this model signifies tbh but just a good practice

File: tests/sentry/api/endpoints/test_organization_weekly_report_project_exclusions.py [hunk 14]
```diff
@@ -0,0 +1,182 @@
...
+        other_project = self.create_project(organization=other_org)
+        with self.feature("organizations:weekly-report-project-exclusions"):
+            response = self.get_response(
+                self.organization.slug,
+                projectIds=[other_project.id],
+            )
+        assert response.status_code == 403
+
+
+class DeleteOrganizationWeeklyReportProjectExclusionDetailsTest(APITestCase):
```
Comment (shashjar) [inline tests/sentry/api/endpoints/test_organization_weekly_report_project_exclusions.py]: might want to separate these tests out to match the API file pattern

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py (hunk 12 above)
Comment (amy-chen23) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py:32]: needed to make mypy happy. alternative was to add type ignore comments which was wonky

File: src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py (hunk 13 above)
Comment (amy-chen23) [reply src/sentry/api/endpoints/organization_weekly_report_project_exclusion_details.py:42]: `self.get_projects()` checks access. Adding tests to confirm that tho

**Review by shashjar — APPROVED** [review]
nice job
